# Test your FastAPI endpoints

GET http://127.0.0.1:8000/?longitude=50.629862255534526&latitude=4.86329867051981&radius=0
Accept: application/json

###

POST http://127.0.0.1:8000/create
Content-Type: application/json

{
  "username": "Xander",
  "data_text": "TEST",
  "data_img_src": "test",
  "location": {
    "type": "Point",
    "coordinates": [50.629862255534526, 4.86329867051981]
  }
}

###
